version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - pip import breathe breathe && python -m breathe.apidoc -o docs/source/dox -p YAP -g class,group xml
python:
   install:
   - requirements: docs/requirements.txt
      